- name: conditions
  hosts: localhost
  become: yes
  tasks:
  - name: check user exists or not
    ansible.builtin.command: id expense
    register: USER
    ignore_errors: true

  - name: print user iformation
    ansible.builtin.debug:
      msg: "User infro: {{USER}}"

