- name: install packages
  hosts: localhost
  become: yes
  tasks:
  - name: install packages
    ansible.builtin.dnf:
      name: "{{item}}"
      state: latest
    loop:
    - mysql
    - nginx
    - postfix


- name: removing packages
  hosts: localhost
  become: yes
  tasks:
  - name: removing packages
    ansible.builtin.dnf:
      name: "{{item}}"
      state: labsent
    loop:
    - mysql
    - nginx
    - postfix